name: Clang Actions
run-name: Running Clang Sanitizers
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - uses: actions/checkout@v2
      - name: Address Sanitizer
        run: |
          clang -g -fsanitize=address examples/address_sanitizer.c -o address
          ./address
      - name: Undefined Behavior Sanitizer
        run: |
          clang -g -fsanitize=undefined examples/undefined_behavior.c -o undefined
          ./undefined
