name: Clang Actions
run-name: Running Clang Sanitizers
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Address Sanitizer
        run: |
          clang -g -fsanitize=address ${{ github.workspace }}/../examples/address_sanitizer.c -c
      - name: Undefined Behavior Sanitizer
        run: |
          clang -g -fsanitize=undefined_behavior.c ${{ github.workspace }}/../examples/address_sanitizer.c -c
